# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6be7b6770723c0702e1a480c6ed1b6f2a423bff42f711e3334a7658b0da6913a54852f73638adb195c22f60dd8d28d384006a3696a98f1e3504ac979daa610c4

test:
  secret_key_base: 8c573a23b296eacc001df06a1e8f7589658e13f3f04379f05a80cb3d2e96fd965152be750def7dca581fa38ea45368a335fc5373be04bb8ad6c9216d180b7af0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
